export type EventSource = "doorkeeper" | "luma";

export interface Event {
  id: string;
  title: string;
  date: string; // ISO 8601
  endDate?: string;
  venue: string;
  address: string;
  source: EventSource;
  tags: string[];
  image: string;
  url: string;
  description: string;
  attendees: number;
}

const tokyoImages = [
  "https://images.unsplash.com/photo-1540959733332-eab4deabeeaf?w=800&q=80",
  "https://images.unsplash.com/photo-1513407030348-c983a97b98d8?w=800&q=80",
  "https://images.unsplash.com/photo-1536098561742-ca998e48cbcc?w=800&q=80",
  "https://images.unsplash.com/photo-1528360983277-13d401cdc186?w=800&q=80",
  "https://images.unsplash.com/photo-1490806843957-31f4c9a91c65?w=800&q=80",
  "https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=800&q=80",
  "https://images.unsplash.com/photo-1555400038-63f5ba517a47?w=800&q=80",
  "https://images.unsplash.com/photo-1542051841857-5f90071e7989?w=800&q=80",
  "https://images.unsplash.com/photo-1551641506-ee5bf4cb45f1?w=800&q=80",
  "https://images.unsplash.com/photo-1464817739973-0128fe77aaa1?w=800&q=80",
];

function img(i: number) {
  return tokyoImages[i % tokyoImages.length];
}

export const mockEvents: Event[] = [
  {
    id: "1",
    title: "Tokyo AI Startup Pitch Night",
    date: "2026-04-05T18:00:00+09:00",
    endDate: "2026-04-05T21:00:00+09:00",
    venue: "WeWork Roppongi Hills",
    address: "6-10-1 Roppongi, Minato-ku, Tokyo",
    source: "doorkeeper",
    tags: ["AI", "startup", "pitch"],
    image: img(0),
    url: "https://www.doorkeeper.jp/events/example-1",
    description: "Monthly pitch event for AI startups in Tokyo. Network with investors and fellow founders.",
    attendees: 120,
  },
  {
    id: "2",
    title: "Luma x Tokyo Tech Founders Meetup",
    date: "2026-04-08T19:00:00+09:00",
    endDate: "2026-04-08T22:00:00+09:00",
    venue: "SHIBUYA QWS",
    address: "2-24-12 Shibuya, Shibuya-ku, Tokyo",
    source: "luma",
    tags: ["networking", "founders", "tech"],
    image: img(1),
    url: "https://lu.ma/tokyo-founders-april",
    description: "Casual meetup for tech founders and builders in Shibuya. Share what you're building.",
    attendees: 85,
  },
  {
    id: "3",
    title: "Deep Tech Japan Summit 2026",
    date: "2026-04-12T09:00:00+09:00",
    endDate: "2026-04-12T18:00:00+09:00",
    venue: "Tokyo International Forum",
    address: "3-5-1 Marunouchi, Chiyoda-ku, Tokyo",
    source: "doorkeeper",
    tags: ["deep tech", "robotics", "biotech"],
    image: img(2),
    url: "https://www.doorkeeper.jp/events/example-3",
    description: "Full-day summit covering robotics, biotech, quantum computing, and advanced materials.",
    attendees: 450,
  },
  {
    id: "4",
    title: "SaaS Growth Hacks: Tokyo Edition",
    date: "2026-04-15T18:30:00+09:00",
    endDate: "2026-04-15T21:00:00+09:00",
    venue: "Spaces Shinjuku",
    address: "1-25-1 Nishi-Shinjuku, Shinjuku-ku, Tokyo",
    source: "luma",
    tags: ["SaaS", "growth", "marketing"],
    image: img(3),
    url: "https://lu.ma/saas-tokyo-april",
    description: "Panel discussion and workshop on growth strategies for B2B SaaS companies.",
    attendees: 95,
  },
  {
    id: "5",
    title: "Web3 & Crypto Tokyo Builders",
    date: "2026-04-18T17:00:00+09:00",
    endDate: "2026-04-18T20:30:00+09:00",
    venue: "CryptoGarage Ginza",
    address: "5-3-1 Ginza, Chuo-ku, Tokyo",
    source: "doorkeeper",
    tags: ["web3", "crypto", "blockchain"],
    image: img(4),
    url: "https://www.doorkeeper.jp/events/example-5",
    description: "Meet the builders pushing the boundaries of decentralized technology in Japan.",
    attendees: 130,
  },
  {
    id: "6",
    title: "Female Founders Tokyo Brunch",
    date: "2026-04-20T10:00:00+09:00",
    endDate: "2026-04-20T13:00:00+09:00",
    venue: "Andaz Tokyo Rooftop",
    address: "1-23-4 Toranomon, Minato-ku, Tokyo",
    source: "luma",
    tags: ["diversity", "founders", "networking"],
    image: img(5),
    url: "https://lu.ma/female-founders-tokyo",
    description: "A monthly brunch gathering celebrating and supporting female entrepreneurs in Tokyo.",
    attendees: 60,
  },
  {
    id: "7",
    title: "Product Hunt Tokyo: Launch Party",
    date: "2026-04-22T18:00:00+09:00",
    endDate: "2026-04-22T22:00:00+09:00",
    venue: "Google Tokyo Office",
    address: "2-15-1 Konan, Minato-ku, Tokyo",
    source: "doorkeeper",
    tags: ["product", "launch", "startup"],
    image: img(6),
    url: "https://www.doorkeeper.jp/events/example-7",
    description: "Celebrate Tokyo's latest product launches. Demo your product to an engaged audience.",
    attendees: 200,
  },
  {
    id: "8",
    title: "Generative AI Workshop: Build Your First Agent",
    date: "2026-04-25T13:00:00+09:00",
    endDate: "2026-04-25T17:00:00+09:00",
    venue: "DMM.com Akihabara Office",
    address: "1-1-1 Sotokanda, Chiyoda-ku, Tokyo",
    source: "luma",
    tags: ["AI", "workshop", "LLM"],
    image: img(7),
    url: "https://lu.ma/genai-workshop-tokyo",
    description: "Hands-on workshop building AI agents with LangChain and OpenAI. Bring your laptop.",
    attendees: 40,
  },
  {
    id: "9",
    title: "Tokyo Fintech Forum Spring 2026",
    date: "2026-04-28T09:30:00+09:00",
    endDate: "2026-04-28T17:00:00+09:00",
    venue: "Nihonbashi Takashimaya",
    address: "2-4-1 Nihonbashi, Chuo-ku, Tokyo",
    source: "doorkeeper",
    tags: ["fintech", "payments", "banking"],
    image: img(8),
    url: "https://www.doorkeeper.jp/events/example-9",
    description: "Spring forum connecting fintech innovators with Japan's leading financial institutions.",
    attendees: 320,
  },
  {
    id: "10",
    title: "Tokyo Dev Night: Rust & Systems Programming",
    date: "2026-05-02T19:00:00+09:00",
    endDate: "2026-05-02T22:00:00+09:00",
    venue: "Mercari Office Roppongi",
    address: "6-10-1 Roppongi, Minato-ku, Tokyo",
    source: "luma",
    tags: ["rust", "dev", "systems"],
    image: img(9),
    url: "https://lu.ma/tokyo-dev-rust",
    description: "Technical talks and demos on Rust for systems programming and WebAssembly.",
    attendees: 75,
  },
  {
    id: "11",
    title: "Startup Weekend Tokyo: EdTech Edition",
    date: "2026-05-08T18:00:00+09:00",
    endDate: "2026-05-10T18:00:00+09:00",
    venue: "Impact Hub Tokyo",
    address: "2-11-3 Meguro, Meguro-ku, Tokyo",
    source: "doorkeeper",
    tags: ["startup", "edtech", "hackathon"],
    image: img(0),
    url: "https://www.doorkeeper.jp/events/example-11",
    description: "54-hour weekend startup event focused on education technology innovations.",
    attendees: 150,
  },
  {
    id: "12",
    title: "Luma Tokyo: Climate Tech Happy Hour",
    date: "2026-05-10T18:30:00+09:00",
    endDate: "2026-05-10T21:00:00+09:00",
    venue: "Trunk Hotel Rooftop",
    address: "5-31 Jingumae, Shibuya-ku, Tokyo",
    source: "luma",
    tags: ["climate", "cleantech", "startup"],
    image: img(1),
    url: "https://lu.ma/climate-tokyo-may",
    description: "Connect with climate tech founders, investors, and enthusiasts in Tokyo.",
    attendees: 110,
  },
  {
    id: "13",
    title: "Japan VC Speed Dating 2026",
    date: "2026-05-14T14:00:00+09:00",
    endDate: "2026-05-14T18:00:00+09:00",
    venue: "Marunouchi Innovation Hub",
    address: "2-1-1 Marunouchi, Chiyoda-ku, Tokyo",
    source: "doorkeeper",
    tags: ["venture capital", "funding", "pitch"],
    image: img(2),
    url: "https://www.doorkeeper.jp/events/example-13",
    description: "5-minute speed pitch sessions with 20+ active Japan-focused VCs.",
    attendees: 80,
  },
  {
    id: "14",
    title: "React Tokyo Meetup #42",
    date: "2026-05-18T19:00:00+09:00",
    endDate: "2026-05-18T22:00:00+09:00",
    venue: "Cybozu Office Aoyama",
    address: "1-8-6 Minami-Aoyama, Minato-ku, Tokyo",
    source: "luma",
    tags: ["react", "frontend", "javascript"],
    image: img(3),
    url: "https://lu.ma/react-tokyo-42",
    description: "Monthly meetup for React developers. Lightning talks, demos, and networking.",
    attendees: 90,
  },
  {
    id: "15",
    title: "IoT & Smart City Tokyo Conference",
    date: "2026-05-21T09:00:00+09:00",
    endDate: "2026-05-21T18:00:00+09:00",
    venue: "Odaiba Big Sight East Hall",
    address: "3-11-1 Ariake, Koto-ku, Tokyo",
    source: "doorkeeper",
    tags: ["IoT", "smart city", "infrastructure"],
    image: img(4),
    url: "https://www.doorkeeper.jp/events/example-15",
    description: "Explore the future of connected cities with keynotes from Tokyo's urban innovators.",
    attendees: 600,
  },
  {
    id: "16",
    title: "Mobile App Founders Circle",
    date: "2026-05-26T18:00:00+09:00",
    endDate: "2026-05-26T21:00:00+09:00",
    venue: "DeNA HQ Shibuya",
    address: "2-21-1 Shibuya, Shibuya-ku, Tokyo",
    source: "luma",
    tags: ["mobile", "app", "consumer"],
    image: img(5),
    url: "https://lu.ma/mobile-founders-may",
    description: "Monthly gathering for mobile-first founders to share learnings and make connections.",
    attendees: 70,
  },
  {
    id: "17",
    title: "Tokyo Blockchain Hackathon",
    date: "2026-05-30T10:00:00+09:00",
    endDate: "2026-05-31T18:00:00+09:00",
    venue: "bitFlyer Headquarters",
    address: "1-12-32 Akasaka, Minato-ku, Tokyo",
    source: "doorkeeper",
    tags: ["blockchain", "hackathon", "web3"],
    image: img(6),
    url: "https://www.doorkeeper.jp/events/example-17",
    description: "48-hour hackathon building on Ethereum, Solana, and Polkadot with ¥1M in prizes.",
    attendees: 200,
  },
  {
    id: "18",
    title: "Medtech & HealthTech Tokyo Roundtable",
    date: "2026-06-03T17:00:00+09:00",
    endDate: "2026-06-03T20:00:00+09:00",
    venue: "Keio University Hospital Innovation Center",
    address: "35 Shinanomachi, Shinjuku-ku, Tokyo",
    source: "luma",
    tags: ["healthtech", "medtech", "biotech"],
    image: img(7),
    url: "https://lu.ma/healthtech-tokyo-june",
    description: "Intimate roundtable connecting medtech startups with hospital innovation leads.",
    attendees: 45,
  },
  {
    id: "19",
    title: "Go Programming Language Tokyo Meetup",
    date: "2026-06-06T18:30:00+09:00",
    endDate: "2026-06-06T21:30:00+09:00",
    venue: "LINE Corporation Shinjuku",
    address: "1-6-1 Nishi-Shinjuku, Shinjuku-ku, Tokyo",
    source: "doorkeeper",
    tags: ["golang", "backend", "cloud"],
    image: img(8),
    url: "https://www.doorkeeper.jp/events/example-19",
    description: "Talks and workshops on Go for high-performance backend systems and microservices.",
    attendees: 100,
  },
  {
    id: "20",
    title: "Tokyo Design x Tech Summit",
    date: "2026-06-10T10:00:00+09:00",
    endDate: "2026-06-10T18:00:00+09:00",
    venue: "Mori Art Museum",
    address: "6-10-1 Roppongi, Minato-ku, Tokyo",
    source: "luma",
    tags: ["design", "UX", "product"],
    image: img(9),
    url: "https://lu.ma/design-tech-tokyo",
    description: "Where design meets technology. Keynotes, workshops, and portfolio showcases.",
    attendees: 280,
  },
  {
    id: "21",
    title: "Cyber Security Japan Forum",
    date: "2026-06-12T09:00:00+09:00",
    endDate: "2026-06-12T17:00:00+09:00",
    venue: "Pacifico Yokohama",
    address: "1-1-1 Minato Mirai, Nishi-ku, Yokohama",
    source: "doorkeeper",
    tags: ["security", "infosec", "enterprise"],
    image: img(0),
    url: "https://www.doorkeeper.jp/events/example-21",
    description: "Japan's premier cyber security gathering for enterprise security professionals.",
    attendees: 500,
  },
  {
    id: "22",
    title: "Startup Grind Tokyo: Monthly Fireside",
    date: "2026-06-16T18:30:00+09:00",
    endDate: "2026-06-16T21:00:00+09:00",
    venue: "Google Campus Tokyo",
    address: "2-15-1 Konan, Minato-ku, Tokyo",
    source: "luma",
    tags: ["startup", "fireside", "inspiration"],
    image: img(1),
    url: "https://lu.ma/startup-grind-tokyo-june",
    description: "Fireside chat with a successful Tokyo startup founder. Q&A and networking after.",
    attendees: 150,
  },
  {
    id: "23",
    title: "E-commerce & DTC Tokyo Workshop",
    date: "2026-06-20T13:00:00+09:00",
    endDate: "2026-06-20T17:00:00+09:00",
    venue: "Rakuten Crimson House",
    address: "1-14-1 Tamagawa, Setagaya-ku, Tokyo",
    source: "doorkeeper",
    tags: ["ecommerce", "DTC", "retail"],
    image: img(2),
    url: "https://www.doorkeeper.jp/events/example-23",
    description: "Practical workshop on scaling direct-to-consumer brands in Japan's e-commerce landscape.",
    attendees: 65,
  },
  {
    id: "24",
    title: "AI Ethics & Policy Roundtable Tokyo",
    date: "2026-06-24T17:00:00+09:00",
    endDate: "2026-06-24T20:00:00+09:00",
    venue: "METI Building Kasumigaseki",
    address: "1-3-1 Kasumigaseki, Chiyoda-ku, Tokyo",
    source: "luma",
    tags: ["AI", "policy", "ethics"],
    image: img(3),
    url: "https://lu.ma/ai-ethics-tokyo",
    description: "Cross-sector dialogue on responsible AI development in Japan. Open to all.",
    attendees: 80,
  },
  {
    id: "25",
    title: "Space Tech Japan: Startup Edition",
    date: "2026-06-28T14:00:00+09:00",
    endDate: "2026-06-28T18:00:00+09:00",
    venue: "JAXA Innovation Hub",
    address: "2-1-1 Sengen, Tsukuba-shi, Ibaraki",
    source: "doorkeeper",
    tags: ["space", "aerospace", "deep tech"],
    image: img(4),
    url: "https://www.doorkeeper.jp/events/example-25",
    description: "Showcasing Japan's emerging space tech startups alongside JAXA researchers.",
    attendees: 120,
  },
  {
    id: "26",
    title: "Tokyo Startup Visa & Legal Workshop",
    date: "2026-07-02T18:00:00+09:00",
    endDate: "2026-07-02T20:30:00+09:00",
    venue: "EY Japan Chiyoda",
    address: "1-2-1 Otemachi, Chiyoda-ku, Tokyo",
    source: "luma",
    tags: ["legal", "visa", "foreign founders"],
    image: img(5),
    url: "https://lu.ma/startup-visa-tokyo",
    description: "Practical guide to Japan startup visas and legal structures for foreign founders.",
    attendees: 55,
  },
  {
    id: "27",
    title: "Data Science Tokyo Symposium",
    date: "2026-07-06T09:30:00+09:00",
    endDate: "2026-07-06T17:30:00+09:00",
    venue: "Hitotsubashi Hall",
    address: "2-1-2 Hitotsubashi, Chiyoda-ku, Tokyo",
    source: "doorkeeper",
    tags: ["data science", "ML", "analytics"],
    image: img(6),
    url: "https://www.doorkeeper.jp/events/example-27",
    description: "Academic and industry talks on machine learning, NLP, and data engineering.",
    attendees: 350,
  },
  {
    id: "28",
    title: "Creator Economy Tokyo: Social + Startups",
    date: "2026-07-09T18:30:00+09:00",
    endDate: "2026-07-09T21:30:00+09:00",
    venue: "Abema Tower",
    address: "16-26 Nanpeidai-cho, Shibuya-ku, Tokyo",
    source: "luma",
    tags: ["creator economy", "social", "media"],
    image: img(7),
    url: "https://lu.ma/creator-economy-tokyo",
    description: "Where content creators and tech startups meet to build the future of media.",
    attendees: 140,
  },
  {
    id: "29",
    title: "Tokyo Hardware Startup Night",
    date: "2026-07-14T18:00:00+09:00",
    endDate: "2026-07-14T21:00:00+09:00",
    venue: "Sony Innovation Lounge",
    address: "1-7-1 Konan, Minato-ku, Tokyo",
    source: "doorkeeper",
    tags: ["hardware", "manufacturing", "IoT"],
    image: img(8),
    url: "https://www.doorkeeper.jp/events/example-29",
    description: "Demo night for hardware startups building physical products in Japan.",
    attendees: 95,
  },
  {
    id: "30",
    title: "Women in Tech Tokyo Annual Gala",
    date: "2026-07-18T17:00:00+09:00",
    endDate: "2026-07-18T22:00:00+09:00",
    venue: "Ritz-Carlton Tokyo",
    address: "9-7-1 Akasaka, Minato-ku, Tokyo",
    source: "luma",
    tags: ["diversity", "women in tech", "awards"],
    image: img(9),
    url: "https://lu.ma/women-in-tech-tokyo-gala",
    description: "Annual celebration of women leading and shaping the tech industry in Japan.",
    attendees: 250,
  },
  {
    id: "31",
    title: "Kubernetes & Cloud Native Tokyo",
    date: "2026-07-22T18:30:00+09:00",
    endDate: "2026-07-22T21:30:00+09:00",
    venue: "Fujitsu Kawasaki HQ",
    address: "4-1-1 Kamikodanaka, Nakahara-ku, Kawasaki",
    source: "doorkeeper",
    tags: ["kubernetes", "cloud", "devops"],
    image: img(0),
    url: "https://www.doorkeeper.jp/events/example-31",
    description: "CNCF Tokyo chapter meetup. Talks on Kubernetes, service mesh, and observability.",
    attendees: 130,
  },
  {
    id: "32",
    title: "Agritech Japan: Future of Food Summit",
    date: "2026-07-25T09:00:00+09:00",
    endDate: "2026-07-25T17:00:00+09:00",
    venue: "Tokyo Metropolitan Central Wholesale Market",
    address: "5-2-1 Toyo, Koto-ku, Tokyo",
    source: "luma",
    tags: ["agritech", "food tech", "sustainability"],
    image: img(1),
    url: "https://lu.ma/agritech-japan-2026",
    description: "Exploring smart farming, vertical agriculture, and alternative proteins in Japan.",
    attendees: 190,
  },
  {
    id: "33",
    title: "Open Source Japan Summit",
    date: "2026-07-30T09:00:00+09:00",
    endDate: "2026-07-30T18:00:00+09:00",
    venue: "Keio University Mita Campus",
    address: "2-15-45 Mita, Minato-ku, Tokyo",
    source: "doorkeeper",
    tags: ["open source", "community", "dev"],
    image: img(2),
    url: "https://www.doorkeeper.jp/events/example-33",
    description: "Japan's largest open source conference with 50+ talks across 4 tracks.",
    attendees: 700,
  },
  {
    id: "34",
    title: "Tokyo PropTech Investors Breakfast",
    date: "2026-08-04T08:00:00+09:00",
    endDate: "2026-08-04T10:00:00+09:00",
    venue: "Mori Building Toranomon Hills",
    address: "1-23-1 Toranomon, Minato-ku, Tokyo",
    source: "luma",
    tags: ["proptech", "real estate", "investing"],
    image: img(3),
    url: "https://lu.ma/proptech-tokyo-breakfast",
    description: "Early morning breakfast for proptech investors and founders. Limited seats.",
    attendees: 35,
  },
  {
    id: "35",
    title: "EdTech Innovation Forum Tokyo",
    date: "2026-08-07T10:00:00+09:00",
    endDate: "2026-08-07T17:00:00+09:00",
    venue: "Waseda University Big Box",
    address: "1-104 Totsukamachi, Shinjuku-ku, Tokyo",
    source: "doorkeeper",
    tags: ["edtech", "education", "learning"],
    image: img(4),
    url: "https://www.doorkeeper.jp/events/example-35",
    description: "Forum on the future of education technology in Japan's K-12 and university markets.",
    attendees: 240,
  },
  {
    id: "36",
    title: "Luma Tokyo: Late-Stage Founders Dinner",
    date: "2026-08-12T19:00:00+09:00",
    endDate: "2026-08-12T22:30:00+09:00",
    venue: "Nobu Tokyo",
    address: "4-1-28 Minami-Azabu, Minato-ku, Tokyo",
    source: "luma",
    tags: ["founders", "growth stage", "exclusive"],
    image: img(5),
    url: "https://lu.ma/late-stage-dinner-tokyo",
    description: "Curated dinner for Series B+ founders. Application required. 20 seats only.",
    attendees: 20,
  },
  {
    id: "37",
    title: "AR/VR Tokyo: Spatial Computing Forum",
    date: "2026-08-16T13:00:00+09:00",
    endDate: "2026-08-16T18:00:00+09:00",
    venue: "teamLab Borderless",
    address: "6-2-8 Aomi, Koto-ku, Tokyo",
    source: "doorkeeper",
    tags: ["AR", "VR", "spatial computing"],
    image: img(6),
    url: "https://www.doorkeeper.jp/events/example-37",
    description: "Experience AR/VR demos from Tokyo's leading spatial computing startups.",
    attendees: 180,
  },
  {
    id: "38",
    title: "Seed Stage Fundraising Workshop",
    date: "2026-08-20T14:00:00+09:00",
    endDate: "2026-08-20T17:00:00+09:00",
    venue: "500 Global Tokyo Office",
    address: "1-8-1 Azumabashi, Sumida-ku, Tokyo",
    source: "luma",
    tags: ["fundraising", "seed", "pitch deck"],
    image: img(7),
    url: "https://lu.ma/seed-fundraising-tokyo",
    description: "Hands-on workshop on crafting seed-stage pitch decks and approaching Tokyo VCs.",
    attendees: 50,
  },
  {
    id: "39",
    title: "Python Tokyo Conference 2026",
    date: "2026-08-25T09:00:00+09:00",
    endDate: "2026-08-26T18:00:00+09:00",
    venue: "Tokyo Tech Ookayama Campus",
    address: "2-12-1 Ookayama, Meguro-ku, Tokyo",
    source: "doorkeeper",
    tags: ["python", "data", "dev"],
    image: img(8),
    url: "https://www.doorkeeper.jp/events/example-39",
    description: "Two-day PyCon-style conference with 60+ talks on Python in data, AI, and web.",
    attendees: 800,
  },
  {
    id: "40",
    title: "Mobility Tech Japan: EV & Autonomous",
    date: "2026-08-28T10:00:00+09:00",
    endDate: "2026-08-28T17:00:00+09:00",
    venue: "Makuhari Messe Hall 11",
    address: "2-1 Nakase, Mihama-ku, Chiba-shi, Chiba",
    source: "luma",
    tags: ["mobility", "EV", "autonomous"],
    image: img(9),
    url: "https://lu.ma/mobility-tech-japan",
    description: "Showcase of electric vehicles, autonomous systems, and future mobility in Japan.",
    attendees: 420,
  },
  {
    id: "41",
    title: "Angel Investor Tokyo Forum",
    date: "2026-09-03T17:30:00+09:00",
    endDate: "2026-09-03T21:00:00+09:00",
    venue: "Palace Hotel Tokyo",
    address: "1-1-1 Marunouchi, Chiyoda-ku, Tokyo",
    source: "doorkeeper",
    tags: ["angel investing", "early stage", "funding"],
    image: img(0),
    url: "https://www.doorkeeper.jp/events/example-41",
    description: "Quarterly forum connecting angel investors with Japan's most promising early-stage startups.",
    attendees: 90,
  },
  {
    id: "42",
    title: "Tech for Social Good Tokyo",
    date: "2026-09-08T13:00:00+09:00",
    endDate: "2026-09-08T18:00:00+09:00",
    venue: "Nihon Foundation Akasaka",
    address: "1-2-2 Akasaka, Minato-ku, Tokyo",
    source: "luma",
    tags: ["social impact", "NGO", "tech for good"],
    image: img(1),
    url: "https://lu.ma/tech-social-good-tokyo",
    description: "Summit for technologists and social entrepreneurs building solutions for social challenges.",
    attendees: 160,
  },
  {
    id: "43",
    title: "Shopify Partners Tokyo Meetup",
    date: "2026-09-12T18:00:00+09:00",
    endDate: "2026-09-12T21:00:00+09:00",
    venue: "Shopify Tokyo Office",
    address: "1-1-2 Nishi-Shinjuku, Shinjuku-ku, Tokyo",
    source: "doorkeeper",
    tags: ["ecommerce", "shopify", "agencies"],
    image: img(2),
    url: "https://www.doorkeeper.jp/events/example-43",
    description: "Connect with Shopify partners building for Japanese merchants. Live demos and updates.",
    attendees: 85,
  },
  {
    id: "44",
    title: "Future of Work Tokyo 2026",
    date: "2026-09-17T09:00:00+09:00",
    endDate: "2026-09-17T17:00:00+09:00",
    venue: "Otemachi Financial City",
    address: "1-9-2 Otemachi, Chiyoda-ku, Tokyo",
    source: "luma",
    tags: ["future of work", "HR tech", "remote"],
    image: img(3),
    url: "https://lu.ma/future-work-tokyo",
    description: "Exploring distributed teams, AI in HR, and workplace transformation in Japan.",
    attendees: 310,
  },
  {
    id: "45",
    title: "Tokyo Startup Ecosystem Report Launch",
    date: "2026-09-22T18:00:00+09:00",
    endDate: "2026-09-22T21:00:00+09:00",
    venue: "KDDI DIGITAL GATE",
    address: "3-2-9 Nishi-Shinjuku, Shinjuku-ku, Tokyo",
    source: "doorkeeper",
    tags: ["ecosystem", "report", "networking"],
    image: img(4),
    url: "https://www.doorkeeper.jp/events/example-45",
    description: "Launch of the 2026 Tokyo Startup Ecosystem Report with panel discussion.",
    attendees: 220,
  },
  {
    id: "46",
    title: "Luma House Tokyo: Founders Weekend",
    date: "2026-09-26T14:00:00+09:00",
    endDate: "2026-09-27T18:00:00+09:00",
    venue: "Luma House Shibuya",
    address: "3-7-1 Shibuya, Shibuya-ku, Tokyo",
    source: "luma",
    tags: ["founders", "community", "weekend"],
    image: img(5),
    url: "https://lu.ma/luma-house-tokyo-sept",
    description: "Two-day immersive founder experience with workshops, dinners, and curated conversations.",
    attendees: 75,
  },
  {
    id: "47",
    title: "Autonomous Robotics Japan Demo Day",
    date: "2026-10-01T10:00:00+09:00",
    endDate: "2026-10-01T17:00:00+09:00",
    venue: "NEDO Kawasaki Innovation Center",
    address: "212-1 Motomachi, Kawasaki-ku, Kawasaki",
    source: "doorkeeper",
    tags: ["robotics", "automation", "AI"],
    image: img(6),
    url: "https://www.doorkeeper.jp/events/example-47",
    description: "Live demos from Japan's leading autonomous robotics startups. Investor attendance required.",
    attendees: 140,
  },
  {
    id: "48",
    title: "Quantum Computing Tokyo: Industry Applications",
    date: "2026-10-06T13:00:00+09:00",
    endDate: "2026-10-06T18:00:00+09:00",
    venue: "IBM Japan Roppongi",
    address: "3-2-12 Roppongi, Minato-ku, Tokyo",
    source: "luma",
    tags: ["quantum", "computing", "research"],
    image: img(7),
    url: "https://lu.ma/quantum-tokyo-oct",
    description: "Industry sessions on quantum computing use cases in logistics, finance, and materials.",
    attendees: 100,
  },
  {
    id: "49",
    title: "Tokyo Y Combinator Alumni Meetup",
    date: "2026-10-10T18:30:00+09:00",
    endDate: "2026-10-10T22:00:00+09:00",
    venue: "Genesia Ventures Office",
    address: "2-3-2 Minami-Aoyama, Minato-ku, Tokyo",
    source: "doorkeeper",
    tags: ["YC", "alumni", "founders"],
    image: img(8),
    url: "https://www.doorkeeper.jp/events/example-49",
    description: "Biannual meetup for YC alumni based in Tokyo. Share updates and reconnect.",
    attendees: 65,
  },
  {
    id: "50",
    title: "Global Startup Battle Japan Finals",
    date: "2026-10-15T09:00:00+09:00",
    endDate: "2026-10-15T18:00:00+09:00",
    venue: "Tokyo Garden Theater",
    address: "3-3 Ariake, Koto-ku, Tokyo",
    source: "luma",
    tags: ["competition", "global", "startup"],
    image: img(9),
    url: "https://lu.ma/gsb-japan-finals",
    description: "Japan finals of the Global Startup Battle. Top 20 startups pitch to an international jury.",
    attendees: 500,
  },
];
